typedef Format = {
	var bold : Format;
	var italic : Format;
	var underline : Format;
	var blink : Format;
	var inverse : Format;
	var strike : Format;
	var black : Format;
	var red : Format;
	var green : Format;
	var yellow : Format;
	var blue : Format;
	var magenta : Format;
	var cyan : Format;
	var white : Format;
	var bgBlack : Format;
	var bgRed : Format;
	var bgGreen : Format;
	var bgYellow : Format;
	var bgBlue : Format;
	var bgMagenta : Format;
	var bgCyan : Format;
	var bgWhite : Format;
	var blackBright : Format;
	var redBright : Format;
	var greenBright : Format;
	var yellowBright : Format;
	var blueBright : Format;
	var magentaBright : Format;
	var cyanBright : Format;
	var whiteBright : Format;
	var bgBlackBright : Format;
	var bgRedBright : Format;
	var bgGreenBright : Format;
	var bgYellowBright : Format;
	var bgBlueBright : Format;
	var bgMagentaBright : Format;
	var bgCyanBright : Format;
	var bgWhiteBright : Format;
	function xterm(color:Float):Format;
	function bgXterm(color:Float):Format;
	function move(x:Float, y:Float):String;
	function moveTo(x:Float, y:Float):String;
	function bol(?n:Float, ?erase:Bool):String;
	function up(n:Float):String;
	function down(n:Float):String;
	function left(n:Float):String;
	function right(n:Float):String;
	var beep : String;
	var reset : String;
	var width : Float;
	var height : Float;
	var xtermSupported : Bool;
};
