extern class CKEDITORTopLevel {
	static var disableAutoInline : Bool;
	static var disableObjectResizing : Bool;
	static var replaceClass : String;
	static var skinName : String;
	static var ALT : Float;
	static var CTRL : Float;
	static var DIALOG_RESIZE_BOTH : Float;
	static var DIALOG_RESIZE_HEIGHT : Float;
	static var DIALOG_RESIZE_NONE : Float;
	static var DIALOG_RESIZE_WIDTH : Float;
	static var ELEMENT_MODE_APPENDTO : Float;
	static var ELEMENT_MODE_INLINE : Float;
	static var ELEMENT_MODE_NONE : Float;
	static var ELEMENT_MODE_REPLACE : Float;
	static var END : Float;
	static var ENTER_BR : Float;
	static var ENTER_P : Float;
	static var EVENT_PHASE_AT_TARGET : Float;
	static var EVENT_PHASE_BUBBLING : Float;
	static var EVENT_PHASE_CAPTURING : Float;
	static var LINEUTILS_AFTER : Float;
	static var LINEUTILS_BEFORE : Float;
	static var LINEUTIS_INSIDE : Float;
	static var NODE_COMMENT : Float;
	static var NODE_DOCUMENT : Float;
	static var NODE_DOCUMENT_FRAGMENT : Float;
	static var NODE_ELEMENT : Float;
	static var NODE_TEXT : Float;
	static var SELECTION_ELEMENT : Float;
	static var SELECTION_NONE : Float;
	static var SELECTION_TEXT : Float;
	static var SHIFT : Float;
	static var SHRINK_ELEMENT : Float;
	static var SHRINK_TEXT : Float;
	static var START : Float;
	static var TRISTATE_DISABLED : Float;
	static var TRISTATE_OFF : Float;
	static var TRISTATE_ON : Float;
	static var UI_BUTTON : String;
	static var UI_MENUBUTTON : String;
	static var UI_PANEL : String;
	static var UI_PANELBUTTON : String;
	static var UI_RICHCOMBO : String;
	static var UI_SEPARATOR : String;
	static var basePath : String;
	static var currentInstance : Editor;
	static var document : dom.Document;
	static var instances : Array<Editor>;
	static var loadFullCoreTimeout : Float;
	static var revision : String;
	static var rnd : Float;
	static var status : String;
	static var timestamp : String;
	static var version : String;
	static function add(editor:Editor):Void;
	static function addCss(css:String):Void;
	static function addTemplate(name:String, source:String):Template;
	static function appendTo(element:String, ?config:Config, ?data:String):Editor;
	static function appendTo(element:HTMLTextAreaElement, ?config:Config, ?data:String):Editor;
	static function domReady():Void;
	static function editorConfig(config:Config):Void;
	static function getCss():String;
	static function getTemplate(name:String):Template;
	static function getUrl(resource:String):String;
	static function inline(element:String, ?instanceConfig:Config):Editor;
	static function inline(element:HTMLTextAreaElement, ?instanceConfig:Config):Editor;
	static function inlineAll():Void;
	static function loadFullCore():Void;
	static function replace(element:String, ?config:Config):Editor;
	static function replace(element:HTMLTextAreaElement, ?config:Config):Editor;
	static function replaceAll(?className:String):Void;
	static function replaceAll(assertionFunction:HTMLTextAreaElement -> Config -> Bool):Void;
}
