typedef IAddOrientation = {
	function millisecond():Date;
	function second():Date;
	function minute():Date;
	function hour():Date;
	function day():Date;
	function week():Date;
	function month():Date;
	function year():Date;
	function milliseconds():Date;
	function seconds():Date;
	function minutes():Date;
	function hours():Date;
	function days():Date;
	function weeks():Date;
	function months():Date;
	function years():Date;
};
typedef IOrientation = {
	>IAddOrientation,
	function monday():Date;
	function tuesday():Date;
	function wednesday():Date;
	function thursday():Date;
	function friday():Date;
	function saturday():Date;
	function sunday():Date;
	function mon():Date;
	function tue():Date;
	function wed():Date;
	function thu():Date;
	function fri():Date;
	function sat():Date;
	function sun():Date;
	function january():Date;
	function february():Date;
	function march():Date;
	function april():Date;
	function may():Date;
	function june():Date;
	function july():Date;
	function august():Date;
	function september():Date;
	function october():Date;
	function november():Date;
	function december():Date;
	function jan():Date;
	function feb():Date;
	function mar():Date;
	function apr():Date;
	function jun():Date;
	function jul():Date;
	function aug():Date;
	function sep():Date;
	function oct():Date;
	function nov():Date;
	function dec():Date;
};
typedef IPredicate = {
	function today():Bool;
	function monday():Bool;
	function tuesday():Bool;
	function wednesday():Bool;
	function thursday():Bool;
	function friday():Bool;
	function saturday():Bool;
	function sunday():Bool;
	function mon():Bool;
	function tue():Bool;
	function wed():Bool;
	function thu():Bool;
	function fri():Bool;
	function sat():Bool;
	function sun():Bool;
	function january():Bool;
	function february():Bool;
	function march():Bool;
	function april():Bool;
	function may():Bool;
	function june():Bool;
	function july():Bool;
	function august():Bool;
	function september():Bool;
	function october():Bool;
	function november():Bool;
	function december():Bool;
	function jan():Bool;
	function feb():Bool;
	function mar():Bool;
	function apr():Bool;
	function jun():Bool;
	function jul():Bool;
	function aug():Bool;
	function sep():Bool;
	function oct():Bool;
	function nov():Bool;
	function dec():Bool;
	function weekday():Bool;
	function day(?date:Date):Bool;
	function week(?date:Date):Bool;
	function month(?date:Date):Bool;
	function year(?date:Date):Bool;
};
typedef IDatePartComparer = {
	function millisecond(?date:Date):Bool;
	function second(?date:Date):Bool;
	function minute(?date:Date):Bool;
	function hour(?date:Date):Bool;
	function day(?date:Date):Bool;
	function week(?date:Date):Bool;
	function month(?date:Date):Bool;
	function year(?date:Date):Bool;
};
typedef IDateElementEvaluator = {
	function ago():Date;
	function before():Date;
	function fromNow():Date;
	function after():Date;
};
typedef IDateElement = {
	function millisecond():IDateElementEvaluator;
	function second():IDateElementEvaluator;
	function minute():IDateElementEvaluator;
	function hour():IDateElementEvaluator;
	function day():IDateElementEvaluator;
	function week():IDateElementEvaluator;
	function month():IDateElementEvaluator;
	function year():IDateElementEvaluator;
	function milliseconds():IDateElementEvaluator;
	function seconds():IDateElementEvaluator;
	function minutes():IDateElementEvaluator;
	function hours():IDateElementEvaluator;
	function days():IDateElementEvaluator;
	function weeks():IDateElementEvaluator;
	function months():IDateElementEvaluator;
	function years():IDateElementEvaluator;
};
typedef IDateLiteral = {
	>ITimeLiteral,
	var day : Float;
	var week : Float;
	var month : Float;
	var year : Float;
};
typedef ITimeLiteral = {
	var millisecond : Float;
	var second : Float;
	var minute : Float;
	var hour : Float;
};
typedef Date = {
	function add(n:Float):sugarpak.IAddOrientation;
	@:overload(function(time:sugarpak.ITimeLiteral):Date { })
	function at(time:String):Date;
	function is():sugarpak.IPredicate;
	function next():sugarpak.IOrientation;
	function last():sugarpak.IOrientation;
	function prev():sugarpak.IOrientation;
	function final():sugarpak.IOrientation;
	function first():sugarpak.IOrientation;
	function second():sugarpak.IOrientation;
	function third():sugarpak.IOrientation;
	function fourth():sugarpak.IOrientation;
	function fifth():sugarpak.IOrientation;
	function previous():sugarpak.IOrientation;
	function same():sugarpak.IDatePartComparer;
	function toObject():sugarpak.IDateLiteral;
};
typedef DateConstructor = {
	var MONDAY : Float;
	var TUESDAY : Float;
	var WEDNESDAY : Float;
	var THURSDAY : Float;
	var FRIDAY : Float;
	var SATURDAY : Float;
	var SUNDAY : Float;
	function fromObject(date:sugarpak.IDateLiteral):Date;
	function next():sugarpak.IOrientation;
	function last():sugarpak.IOrientation;
	function prev():sugarpak.IOrientation;
	function previous():sugarpak.IOrientation;
	function january():Date;
	function february():Date;
	function march():Date;
	function april():Date;
	function may():Date;
	function june():Date;
	function july():Date;
	function august():Date;
	function september():Date;
	function october():Date;
	function november():Date;
	function december():Date;
	function monday():Date;
	function tuesday():Date;
	function wednesday():Date;
	function thursday():Date;
	function friday():Date;
	function saturday():Date;
	function sunday():Date;
	function mon():Date;
	function tue():Date;
	function wed():Date;
	function thu():Date;
	function fri():Date;
	function sat():Date;
	function sun():Date;
	function jan():Date;
	function feb():Date;
	function mar():Date;
	function apr():Date;
	function jun():Date;
	function jul():Date;
	function aug():Date;
	function sep():Date;
	function oct():Date;
	function nov():Date;
	function dec():Date;
};
typedef Number = {
	>sugarpak.IDateElement,
};
