typedef Base = {
	var Adobebricks : Dynamic;
	var Algae : Dynamic;
	var Bahamation : Dynamic;
	var base : Dynamic;
	var blue : Dynamic;
	var BlueDusk : Dynamic;
	var Charged : Dynamic;
	var Chris : Dynamic;
	var Claro : Dynamic;
	var CubanShirts : Dynamic;
	var cyan : Dynamic;
	var Desert : Dynamic;
	var Distinctive : Dynamic;
	var Dollar : Dynamic;
	var Electric : Dynamic;
	var Grasshopper : Dynamic;
	var Grasslands : Dynamic;
	var green : Dynamic;
	var GreySkies : Dynamic;
	var Harmony : Dynamic;
	var IndigoNation : Dynamic;
	var Ireland : Dynamic;
	var Julie : Dynamic;
	var MiamiNice : Dynamic;
	var Midwest : Dynamic;
	var Minty : Dynamic;
	var orange : Dynamic;
	var PrimaryColors : Dynamic;
	var purple : Dynamic;
	var PurpleRain : Dynamic;
	var red : Dynamic;
	var Renkoo : Dynamic;
	var RoyalPurples : Dynamic;
	var SageToLime : Dynamic;
	var Shrooms : Dynamic;
	var Tom : Dynamic;
	var Tufte : Dynamic;
	var WatersEdge : Dynamic;
	var Wetland : Dynamic;
	function generateFills(colors:Array<Dynamic>, fillPattern:Dynamic, lumFrom:Float, lumTo:Float):Void;
	function generateGradientByIntensity(color:dojo._base.Color, intensityMap:Array<Dynamic>):Void;
	function generateMiniTheme(colors:Array<Dynamic>, fillPattern:Dynamic, lumFrom:Float, lumTo:Float, lumStroke:Float):Void;
	function updateFills(themes:Array<Dynamic>, fillPattern:Dynamic, lumFrom:Float, lumTo:Float):Void;
};
