typedef Hash = { };
typedef DatePicker = { };
typedef PageTurningUtils = { };
extern class Scrollable {
	var constraint : Bool;
	var dirLock : Bool;
	var disableFlashScrollBar : Bool;
	var fadeScrollBar : Bool;
	var fixedFooterHeight : Float;
	var fixedHeaderHeight : Float;
	var height : String;
	var isLocalFooter : Bool;
	var propagatable : Bool;
	var scrollBar : Bool;
	var scrollDir : String;
	var scrollType : Float;
	var threshold : Float;
	var touchNode : HTMLElement;
	var weight : Float;
	function abort():Void;
	function addCover():Void;
	function adjustDestination(to:Dynamic, pos:Dynamic, dim:Dynamic):Bool;
	function calcScrollBarPos(to:Dynamic):Dynamic;
	function calcSpeed(distance:Float, time:Float):Float;
	function cleanup():Void;
	function createMask():Void;
	function findDisp(node:HTMLElement):Dynamic;
	function flashScrollBar():Void;
	function getDim():Dynamic;
	function getPos():Dynamic;
	function getScreenSize():Dynamic;
	function getSpeed():Dynamic;
	function hideScrollBar():Void;
	function init(params:Dynamic):Void;
	function isFormElement(node:HTMLElement):Bool;
	function isTopLevel():Bool;
	function makeTranslateStr(to:Dynamic):String;
	function removeCover():Void;
	function resetScrollBar():Void;
	function resize(e:Dynamic):Void;
	function scrollIntoView(node:HTMLElement, alignWithTop:Bool, duration:Float):Void;
	function scrollScrollBarTo(to:Dynamic):Void;
	function scrollTo(to:Dynamic, doNotMoveScrollBar:Bool, node:HTMLElement):Void;
	function setKeyframes(from:Dynamic, to:Dynamic, idx:Float):Void;
	function setSelectable(node:HTMLElement, selectable:Bool):Void;
	function showScrollBar():Void;
	function slideScrollBarTo(to:Dynamic, duration:Float, easing:String):Void;
	function slideTo(to:Dynamic, duration:Float, easing:String):Void;
	function stopAnimation():Void;
}
typedef TimePicker = { };
