@:enum abstract AuthenticationProtocol(Int) {
	var basic = 0;
	var digest = 1;
	var ntlm = 2;
	var kerberos = 3;
	var negotiate = 4;
	var credSsp = 5;
	var custom = 6;
}
@:enum abstract CredentialSaveOption(Int) {
	var unselected = 0;
	var selected = 1;
	var hidden = 2;
}
typedef ICredentialPickerOptions = {
	var alwaysDisplayDialog : Bool;
	var authenticationProtocol : Windows.Security.Credentials.UI.AuthenticationProtocol;
	var callerSavesCredential : Bool;
	var caption : String;
	var credentialSaveOption : Windows.Security.Credentials.UI.CredentialSaveOption;
	var customAuthenticationProtocol : String;
	var errorCode : Float;
	var message : String;
	var previousCredential : Windows.Storage.Streams.IBuffer;
	var targetName : String;
};
extern class CredentialPickerOptions {
	var alwaysDisplayDialog : Bool;
	var authenticationProtocol : Windows.Security.Credentials.UI.AuthenticationProtocol;
	var callerSavesCredential : Bool;
	var caption : String;
	var credentialSaveOption : Windows.Security.Credentials.UI.CredentialSaveOption;
	var customAuthenticationProtocol : String;
	var errorCode : Float;
	var message : String;
	var previousCredential : Windows.Storage.Streams.IBuffer;
	var targetName : String;
}
typedef ICredentialPickerStatics = {
	@:overload(function(targetName:String, message:String):Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.CredentialPickerResults> { })
	@:overload(function(targetName:String, message:String, caption:String):Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.CredentialPickerResults> { })
	function pickAsync(options:Windows.Security.Credentials.UI.CredentialPickerOptions):Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.CredentialPickerResults>;
};
extern class CredentialPickerResults {
	var credential : Windows.Storage.Streams.IBuffer;
	var credentialDomainName : String;
	var credentialPassword : String;
	var credentialSaveOption : Windows.Security.Credentials.UI.CredentialSaveOption;
	var credentialSaved : Bool;
	var credentialUserName : String;
	var errorCode : Float;
}
extern class CredentialPicker {
	@:overload(function(targetName:String, message:String):Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.CredentialPickerResults> { })
	@:overload(function(targetName:String, message:String, caption:String):Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.CredentialPickerResults> { })
	static function pickAsync(options:Windows.Security.Credentials.UI.CredentialPickerOptions):Windows.Foundation.IAsyncOperation<Windows.Security.Credentials.UI.CredentialPickerResults>;
}
typedef ICredentialPickerResults = {
	var credential : Windows.Storage.Streams.IBuffer;
	var credentialDomainName : String;
	var credentialPassword : String;
	var credentialSaveOption : Windows.Security.Credentials.UI.CredentialSaveOption;
	var credentialSaved : Bool;
	var credentialUserName : String;
	var errorCode : Float;
};
typedef IColors = { };
typedef IColorsStatics = {
	var aliceBlue : Windows.UI.Color;
	var antiqueWhite : Windows.UI.Color;
	var aqua : Windows.UI.Color;
	var aquamarine : Windows.UI.Color;
	var azure : Windows.UI.Color;
	var beige : Windows.UI.Color;
	var bisque : Windows.UI.Color;
	var black : Windows.UI.Color;
	var blanchedAlmond : Windows.UI.Color;
	var blue : Windows.UI.Color;
	var blueViolet : Windows.UI.Color;
	var brown : Windows.UI.Color;
	var burlyWood : Windows.UI.Color;
	var cadetBlue : Windows.UI.Color;
	var chartreuse : Windows.UI.Color;
	var chocolate : Windows.UI.Color;
	var coral : Windows.UI.Color;
	var cornflowerBlue : Windows.UI.Color;
	var cornsilk : Windows.UI.Color;
	var crimson : Windows.UI.Color;
	var cyan : Windows.UI.Color;
	var darkBlue : Windows.UI.Color;
	var darkCyan : Windows.UI.Color;
	var darkGoldenrod : Windows.UI.Color;
	var darkGray : Windows.UI.Color;
	var darkGreen : Windows.UI.Color;
	var darkKhaki : Windows.UI.Color;
	var darkMagenta : Windows.UI.Color;
	var darkOliveGreen : Windows.UI.Color;
	var darkOrange : Windows.UI.Color;
	var darkOrchid : Windows.UI.Color;
	var darkRed : Windows.UI.Color;
	var darkSalmon : Windows.UI.Color;
	var darkSeaGreen : Windows.UI.Color;
	var darkSlateBlue : Windows.UI.Color;
	var darkSlateGray : Windows.UI.Color;
	var darkTurquoise : Windows.UI.Color;
	var darkViolet : Windows.UI.Color;
	var deepPink : Windows.UI.Color;
	var deepSkyBlue : Windows.UI.Color;
	var dimGray : Windows.UI.Color;
	var dodgerBlue : Windows.UI.Color;
	var firebrick : Windows.UI.Color;
	var floralWhite : Windows.UI.Color;
	var forestGreen : Windows.UI.Color;
	var fuchsia : Windows.UI.Color;
	var gainsboro : Windows.UI.Color;
	var ghostWhite : Windows.UI.Color;
	var gold : Windows.UI.Color;
	var goldenrod : Windows.UI.Color;
	var gray : Windows.UI.Color;
	var green : Windows.UI.Color;
	var greenYellow : Windows.UI.Color;
	var honeydew : Windows.UI.Color;
	var hotPink : Windows.UI.Color;
	var indianRed : Windows.UI.Color;
	var indigo : Windows.UI.Color;
	var ivory : Windows.UI.Color;
	var khaki : Windows.UI.Color;
	var lavender : Windows.UI.Color;
	var lavenderBlush : Windows.UI.Color;
	var lawnGreen : Windows.UI.Color;
	var lemonChiffon : Windows.UI.Color;
	var lightBlue : Windows.UI.Color;
	var lightCoral : Windows.UI.Color;
	var lightCyan : Windows.UI.Color;
	var lightGoldenrodYellow : Windows.UI.Color;
	var lightGray : Windows.UI.Color;
	var lightGreen : Windows.UI.Color;
	var lightPink : Windows.UI.Color;
	var lightSalmon : Windows.UI.Color;
	var lightSeaGreen : Windows.UI.Color;
	var lightSkyBlue : Windows.UI.Color;
	var lightSlateGray : Windows.UI.Color;
	var lightSteelBlue : Windows.UI.Color;
	var lightYellow : Windows.UI.Color;
	var lime : Windows.UI.Color;
	var limeGreen : Windows.UI.Color;
	var linen : Windows.UI.Color;
	var magenta : Windows.UI.Color;
	var maroon : Windows.UI.Color;
	var mediumAquamarine : Windows.UI.Color;
	var mediumBlue : Windows.UI.Color;
	var mediumOrchid : Windows.UI.Color;
	var mediumPurple : Windows.UI.Color;
	var mediumSeaGreen : Windows.UI.Color;
	var mediumSlateBlue : Windows.UI.Color;
	var mediumSpringGreen : Windows.UI.Color;
	var mediumTurquoise : Windows.UI.Color;
	var mediumVioletRed : Windows.UI.Color;
	var midnightBlue : Windows.UI.Color;
	var mintCream : Windows.UI.Color;
	var mistyRose : Windows.UI.Color;
	var moccasin : Windows.UI.Color;
	var navajoWhite : Windows.UI.Color;
	var navy : Windows.UI.Color;
	var oldLace : Windows.UI.Color;
	var olive : Windows.UI.Color;
	var oliveDrab : Windows.UI.Color;
	var orange : Windows.UI.Color;
	var orangeRed : Windows.UI.Color;
	var orchid : Windows.UI.Color;
	var paleGoldenrod : Windows.UI.Color;
	var paleGreen : Windows.UI.Color;
	var paleTurquoise : Windows.UI.Color;
	var paleVioletRed : Windows.UI.Color;
	var papayaWhip : Windows.UI.Color;
	var peachPuff : Windows.UI.Color;
	var peru : Windows.UI.Color;
	var pink : Windows.UI.Color;
	var plum : Windows.UI.Color;
	var powderBlue : Windows.UI.Color;
	var purple : Windows.UI.Color;
	var red : Windows.UI.Color;
	var rosyBrown : Windows.UI.Color;
	var royalBlue : Windows.UI.Color;
	var saddleBrown : Windows.UI.Color;
	var salmon : Windows.UI.Color;
	var sandyBrown : Windows.UI.Color;
	var seaGreen : Windows.UI.Color;
	var seaShell : Windows.UI.Color;
	var sienna : Windows.UI.Color;
	var silver : Windows.UI.Color;
	var skyBlue : Windows.UI.Color;
	var slateBlue : Windows.UI.Color;
	var slateGray : Windows.UI.Color;
	var snow : Windows.UI.Color;
	var springGreen : Windows.UI.Color;
	var steelBlue : Windows.UI.Color;
	var tan : Windows.UI.Color;
	var teal : Windows.UI.Color;
	var thistle : Windows.UI.Color;
	var tomato : Windows.UI.Color;
	var transparent : Windows.UI.Color;
	var turquoise : Windows.UI.Color;
	var violet : Windows.UI.Color;
	var wheat : Windows.UI.Color;
	var white : Windows.UI.Color;
	var whiteSmoke : Windows.UI.Color;
	var yellow : Windows.UI.Color;
	var yellowGreen : Windows.UI.Color;
};
extern class Colors {
	static var aliceBlue : Windows.UI.Color;
	static var antiqueWhite : Windows.UI.Color;
	static var aqua : Windows.UI.Color;
	static var aquamarine : Windows.UI.Color;
	static var azure : Windows.UI.Color;
	static var beige : Windows.UI.Color;
	static var bisque : Windows.UI.Color;
	static var black : Windows.UI.Color;
	static var blanchedAlmond : Windows.UI.Color;
	static var blue : Windows.UI.Color;
	static var blueViolet : Windows.UI.Color;
	static var brown : Windows.UI.Color;
	static var burlyWood : Windows.UI.Color;
	static var cadetBlue : Windows.UI.Color;
	static var chartreuse : Windows.UI.Color;
	static var chocolate : Windows.UI.Color;
	static var coral : Windows.UI.Color;
	static var cornflowerBlue : Windows.UI.Color;
	static var cornsilk : Windows.UI.Color;
	static var crimson : Windows.UI.Color;
	static var cyan : Windows.UI.Color;
	static var darkBlue : Windows.UI.Color;
	static var darkCyan : Windows.UI.Color;
	static var darkGoldenrod : Windows.UI.Color;
	static var darkGray : Windows.UI.Color;
	static var darkGreen : Windows.UI.Color;
	static var darkKhaki : Windows.UI.Color;
	static var darkMagenta : Windows.UI.Color;
	static var darkOliveGreen : Windows.UI.Color;
	static var darkOrange : Windows.UI.Color;
	static var darkOrchid : Windows.UI.Color;
	static var darkRed : Windows.UI.Color;
	static var darkSalmon : Windows.UI.Color;
	static var darkSeaGreen : Windows.UI.Color;
	static var darkSlateBlue : Windows.UI.Color;
	static var darkSlateGray : Windows.UI.Color;
	static var darkTurquoise : Windows.UI.Color;
	static var darkViolet : Windows.UI.Color;
	static var deepPink : Windows.UI.Color;
	static var deepSkyBlue : Windows.UI.Color;
	static var dimGray : Windows.UI.Color;
	static var dodgerBlue : Windows.UI.Color;
	static var firebrick : Windows.UI.Color;
	static var floralWhite : Windows.UI.Color;
	static var forestGreen : Windows.UI.Color;
	static var fuchsia : Windows.UI.Color;
	static var gainsboro : Windows.UI.Color;
	static var ghostWhite : Windows.UI.Color;
	static var gold : Windows.UI.Color;
	static var goldenrod : Windows.UI.Color;
	static var gray : Windows.UI.Color;
	static var green : Windows.UI.Color;
	static var greenYellow : Windows.UI.Color;
	static var honeydew : Windows.UI.Color;
	static var hotPink : Windows.UI.Color;
	static var indianRed : Windows.UI.Color;
	static var indigo : Windows.UI.Color;
	static var ivory : Windows.UI.Color;
	static var khaki : Windows.UI.Color;
	static var lavender : Windows.UI.Color;
	static var lavenderBlush : Windows.UI.Color;
	static var lawnGreen : Windows.UI.Color;
	static var lemonChiffon : Windows.UI.Color;
	static var lightBlue : Windows.UI.Color;
	static var lightCoral : Windows.UI.Color;
	static var lightCyan : Windows.UI.Color;
	static var lightGoldenrodYellow : Windows.UI.Color;
	static var lightGray : Windows.UI.Color;
	static var lightGreen : Windows.UI.Color;
	static var lightPink : Windows.UI.Color;
	static var lightSalmon : Windows.UI.Color;
	static var lightSeaGreen : Windows.UI.Color;
	static var lightSkyBlue : Windows.UI.Color;
	static var lightSlateGray : Windows.UI.Color;
	static var lightSteelBlue : Windows.UI.Color;
	static var lightYellow : Windows.UI.Color;
	static var lime : Windows.UI.Color;
	static var limeGreen : Windows.UI.Color;
	static var linen : Windows.UI.Color;
	static var magenta : Windows.UI.Color;
	static var maroon : Windows.UI.Color;
	static var mediumAquamarine : Windows.UI.Color;
	static var mediumBlue : Windows.UI.Color;
	static var mediumOrchid : Windows.UI.Color;
	static var mediumPurple : Windows.UI.Color;
	static var mediumSeaGreen : Windows.UI.Color;
	static var mediumSlateBlue : Windows.UI.Color;
	static var mediumSpringGreen : Windows.UI.Color;
	static var mediumTurquoise : Windows.UI.Color;
	static var mediumVioletRed : Windows.UI.Color;
	static var midnightBlue : Windows.UI.Color;
	static var mintCream : Windows.UI.Color;
	static var mistyRose : Windows.UI.Color;
	static var moccasin : Windows.UI.Color;
	static var navajoWhite : Windows.UI.Color;
	static var navy : Windows.UI.Color;
	static var oldLace : Windows.UI.Color;
	static var olive : Windows.UI.Color;
	static var oliveDrab : Windows.UI.Color;
	static var orange : Windows.UI.Color;
	static var orangeRed : Windows.UI.Color;
	static var orchid : Windows.UI.Color;
	static var paleGoldenrod : Windows.UI.Color;
	static var paleGreen : Windows.UI.Color;
	static var paleTurquoise : Windows.UI.Color;
	static var paleVioletRed : Windows.UI.Color;
	static var papayaWhip : Windows.UI.Color;
	static var peachPuff : Windows.UI.Color;
	static var peru : Windows.UI.Color;
	static var pink : Windows.UI.Color;
	static var plum : Windows.UI.Color;
	static var powderBlue : Windows.UI.Color;
	static var purple : Windows.UI.Color;
	static var red : Windows.UI.Color;
	static var rosyBrown : Windows.UI.Color;
	static var royalBlue : Windows.UI.Color;
	static var saddleBrown : Windows.UI.Color;
	static var salmon : Windows.UI.Color;
	static var sandyBrown : Windows.UI.Color;
	static var seaGreen : Windows.UI.Color;
	static var seaShell : Windows.UI.Color;
	static var sienna : Windows.UI.Color;
	static var silver : Windows.UI.Color;
	static var skyBlue : Windows.UI.Color;
	static var slateBlue : Windows.UI.Color;
	static var slateGray : Windows.UI.Color;
	static var snow : Windows.UI.Color;
	static var springGreen : Windows.UI.Color;
	static var steelBlue : Windows.UI.Color;
	static var tan : Windows.UI.Color;
	static var teal : Windows.UI.Color;
	static var thistle : Windows.UI.Color;
	static var tomato : Windows.UI.Color;
	static var transparent : Windows.UI.Color;
	static var turquoise : Windows.UI.Color;
	static var violet : Windows.UI.Color;
	static var wheat : Windows.UI.Color;
	static var white : Windows.UI.Color;
	static var whiteSmoke : Windows.UI.Color;
	static var yellow : Windows.UI.Color;
	static var yellowGreen : Windows.UI.Color;
}
typedef Color = {
	var a : Float;
	var r : Float;
	var g : Float;
	var b : Float;
};
typedef IColorHelper = { };
typedef IColorHelperStatics = {
	function fromArgb(a:Float, r:Float, g:Float, b:Float):Windows.UI.Color;
};
extern class ColorHelper {
	static function fromArgb(a:Float, r:Float, g:Float, b:Float):Windows.UI.Color;
}
