extern class DriveUnits {
	static var ACRES : Dynamic;
	static var ARES : Dynamic;
	static var CENTIMETERS : Dynamic;
	static var DECIMAL_DEGREES : Dynamic;
	static var DECIMETERS : Dynamic;
	static var DEGREE_MINUTE_SECONDS : Dynamic;
	static var FEET : Dynamic;
	static var HECTARES : Dynamic;
	static var INCHES : Dynamic;
	static var KILOMETERS : Dynamic;
	static var METERS : Dynamic;
	static var MILES : Dynamic;
	static var MILLIMETERS : Dynamic;
	static var MINUTES : Dynamic;
	static var NAUTICAL_MILES : Dynamic;
	static var POINTS : Dynamic;
	static var SQUARE_CENTIMETERS : Dynamic;
	static var SQUARE_DECIMETERS : Dynamic;
	static var SQUARE_FEET : Dynamic;
	static var SQUARE_INCHES : Dynamic;
	static var SQUARE_KILOMETERS : Dynamic;
	static var SQUARE_METERS : Dynamic;
	static var SQUARE_MILES : Dynamic;
	static var SQUARE_MILLIMETERS : Dynamic;
	static var SQUARE_YARDS : Dynamic;
	static var UNKNOWN : Dynamic;
	static var YARDS : Dynamic;
}
