typedef _phone2numeric = {
	var a : Float;
	var b : Float;
	var c : Float;
	var d : Float;
	var e : Float;
	var f : Float;
	var g : Float;
	var h : Float;
	var i : Float;
	var j : Float;
	var k : Float;
	var l : Float;
	var m : Float;
	var n : Float;
	var o : Float;
	var p : Float;
	var r : Float;
	var s : Float;
	var t : Float;
	var u : Float;
	var v : Float;
	var w : Float;
	var x : Float;
	var y : Float;
};
typedef Lists = {
	function dictsort(value:Dynamic, arg:Dynamic):Dynamic;
	function dictsortreversed(value:Dynamic, arg:Dynamic):Dynamic;
	function first(value:Dynamic):String;
	function join(value:Dynamic, arg:Dynamic):Dynamic;
	function length(value:Dynamic):Dynamic;
	function length_is(value:Dynamic, arg:Dynamic):Bool;
	function random(value:Dynamic):Dynamic;
	function slice(value:Dynamic, arg:Dynamic):Dynamic;
	function unordered_list(value:Dynamic):Dynamic;
};
typedef Strings = {
	function addslashes(value:Dynamic):Dynamic;
	function capfirst(value:Dynamic):Float;
	function center(value:Dynamic, arg:Dynamic):String;
	function cut(value:Dynamic, arg:Dynamic):Dynamic;
	function fix_ampersands(value:Dynamic):Dynamic;
	function floatformat(value:Dynamic, arg:Dynamic):Dynamic;
	function iriencode(value:Dynamic):Dynamic;
	function linenumbers(value:Dynamic):Dynamic;
	function ljust(value:Dynamic, arg:Dynamic):String;
	function lower(value:Dynamic):Dynamic;
	function make_list(value:Dynamic):Array<Dynamic>;
	function rjust(value:Dynamic, arg:Dynamic):String;
	function slugify(value:Dynamic):Dynamic;
	function stringformat(value:Dynamic, arg:Dynamic):Dynamic;
	function title(value:Dynamic):String;
	function truncatewords(value:Dynamic, arg:Float):Dynamic;
	function truncatewords_html(value:Dynamic, arg:Dynamic):String;
	function upper(value:Dynamic):Dynamic;
	function urlencode(value:Dynamic):Dynamic;
	function urlize(value:Dynamic):Dynamic;
	function urlizetrunc(value:Dynamic, arg:Dynamic):Dynamic;
	function wordcount(value:Dynamic):Float;
	function wordwrap(value:String, arg:Dynamic):Dynamic;
};
