typedef IAnimationMethodResponse = {
	function execute():Promise<Dynamic>;
};
extern class WinJS.UI.AnimationTopLevel {
	static function continuumForwardIn(incomingPage:Dynamic, incomingItemRoot:Dynamic, incomingItemContent:Dynamic):Promise<Dynamic>;
	static function continuumForwardOut(outgoingPage:Dynamic, outgoingItem:Dynamic):Promise<Dynamic>;
	static function continuumBackwardIn(incomingPage:Dynamic, incomingItem:Dynamic):Promise<Dynamic>;
	static function continuumBackwardOut(outgoingPage:Dynamic):Promise<Dynamic>;
	static function createAddToListAnimation(added:Dynamic, affected:Dynamic):IAnimationMethodResponse;
	static function createAddToSearchListAnimation(added:Dynamic, affected:Dynamic):IAnimationMethodResponse;
	static function createCollapseAnimation(hidden:Dynamic, affected:Dynamic):IAnimationMethodResponse;
	static function createDeleteFromListAnimation(deleted:Dynamic, remaining:Dynamic):IAnimationMethodResponse;
	static function createDeleteFromSearchListAnimation(deleted:Dynamic, remaining:Dynamic):IAnimationMethodResponse;
	static function createExpandAnimation(revealed:Dynamic, affected:Dynamic):IAnimationMethodResponse;
	static function createPageNavigationAnimation(currentPreferredAnimation:PageNavigationAnimation, nextPreferredAnimation:PageNavigationAnimation, movingBackwards:Bool):{ var enter : Void -> Dynamic; var exit : Void -> Dynamic; };
	static function createPeekAnimation(element:Dynamic):IAnimationMethodResponse;
	static function createRepositionAnimation(element:Dynamic):IAnimationMethodResponse;
	static function crossFade(incoming:Dynamic, outgoing:Dynamic):Promise<Dynamic>;
	static function dragBetweenEnter(target:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function dragBetweenLeave(target:Dynamic):Promise<Dynamic>;
	static function dragSourceEnd(dragSource:Dynamic, ?offset:Dynamic, ?affected:Dynamic):Promise<Dynamic>;
	static function dragSourceStart(dragSource:Dynamic, ?affected:Dynamic):Promise<Dynamic>;
	static function enterContent(incoming:Dynamic, ?offset:Dynamic, ?options:Dynamic):Promise<Dynamic>;
	static function enterPage(element:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function exitContent(outgoing:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function exitPage(outgoing:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function fadeIn(shown:Dynamic):Promise<Dynamic>;
	static function fadeOut(hidden:Dynamic):Promise<Dynamic>;
	static function hideEdgeUI(element:Dynamic, ?offset:Dynamic, ?options:Dynamic):Promise<Dynamic>;
	static function hidePanel(element:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function hidePopup(element:Dynamic):Promise<Dynamic>;
	static function pointerDown(element:Dynamic):Promise<Dynamic>;
	static function pointerUp(element:Dynamic):Promise<Dynamic>;
	static function showEdgeUI(element:Dynamic, ?offset:Dynamic, ?options:Dynamic):Promise<Dynamic>;
	static function showPanel(element:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function showPopup(element:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function slideDown(outgoing:Dynamic):Promise<Dynamic>;
	static function slideUp(outgoing:Dynamic):Promise<Dynamic>;
	static function slideRightIn(page:Dynamic, firstIncomingElements:Dynamic, secondIncomingElements:Dynamic, thirdIncomingElements:Dynamic):Promise<Dynamic>;
	static function slideRightOut(page:Dynamic, firstOutgoingElements:Dynamic, secondOutgoingElements:Dynamic, thirdOutgoingElements:Dynamic):Promise<Dynamic>;
	static function slideLeftIn(page:Dynamic, firstIncomingElements:Dynamic, secondIncomingElements:Dynamic, thirdIncomingElements:Dynamic):Promise<Dynamic>;
	static function slideLeftOut(page:Dynamic, firstOutgoingElements:Dynamic, secondOutgoingElements:Dynamic, thirdOutgoingElements:Dynamic):Promise<Dynamic>;
	static function swipeDeselect(deselected:Dynamic, selection:Dynamic):Promise<Dynamic>;
	static function swipeReveal(target:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
	static function swipeSelect(selected:Dynamic, selection:Dynamic):Promise<Dynamic>;
	static function turnstileForwardIn(incoming:Dynamic):Promise<Dynamic>;
	static function turnstileForwardOut(outgoing:Dynamic):Promise<Dynamic>;
	static function turnstileBackwardIn(incoming:Dynamic):Promise<Dynamic>;
	static function turnstileBackwardOut(outgoing:Dynamic):Promise<Dynamic>;
	static function updateBadge(incoming:Dynamic, ?offset:Dynamic):Promise<Dynamic>;
}
