extern class _base {
	function new(inProps:Dynamic):Void;
	var alwaysEditing : Bool;
	var classes : String;
	var defaultValue : String;
	var draggable : Bool;
	var editable : Bool;
	var formatter : Dynamic;
	var hidden : Bool;
	var noresize : Bool;
	var styles : String;
	var value : Dynamic;
	function AlwaysEdit():Void;
	function apply(inRowIndex:Float):Void;
	function applyEdit(inValue:Dynamic, inRowIndex:Dynamic):Void;
	function Bool():Void;
	function cancel(inRowIndex:Float):Void;
	function cancelEdit(inRowIndex:Dynamic):Void;
	function cancelFormatNode():Void;
	function canResize():Dynamic;
	function Cell():Void;
	function dispatchEvent(m:Dynamic, e:Dynamic):Dynamic;
	function focus(inRowIndex:Float, inNode:Dynamic):Void;
	function format(inRowIndex:Float, inItem:Dynamic):Dynamic;
	function formatEditing(inDatum:Dynamic, inRowIndex:Float):Dynamic;
	function formatNode(inNode:Dynamic, inDatum:Dynamic, inRowIndex:Float):Void;
	function getEditNode(inRowIndex:Dynamic):Float;
	function getHeaderNode():Dynamic;
	function getNode(inRowIndex:Float):Dynamic;
	function getValue(inRowIndex:Float):Dynamic;
	function isFlex():Dynamic;
	function markupFactory(node:Dynamic, cellDef:Dynamic):Void;
	function needFormatNode(inDatum:Dynamic, inRowIndex:Dynamic):Void;
	function registerOnBlur(inNode:Dynamic, inRowIndex:Dynamic):Void;
	function restore(inRowIndex:Float):Void;
	function RowIndex():Void;
	function save(inRowIndex:Float):Void;
	function Select():Void;
	function setValue(inRowIndex:Float, inValue:Dynamic):Void;
}
