typedef Client = {
	function debug():UniversalAnalytics.Client;
	function send():Void;
	@:overload(function(path:String, ?callback:Dynamic -> Void):Void { })
	@:overload(function(params:Dynamic):Client { })
	@:overload(function(params:Dynamic, ?callback:Dynamic -> Void):Void { })
	@:overload(function(path:String, hostname:String):Client { })
	@:overload(function(path:String, hostname:String, ?callback:Dynamic -> Void):Void { })
	@:overload(function(path:String, title:String, hostname:String):Client { })
	@:overload(function(path:String, title:String, hostname:String, ?callback:Dynamic -> Void):Void { })
	function pageview(path:String):Client;
	@:overload(function(category:String, action:String, ?callback:Dynamic -> Void):Void { })
	@:overload(function(category:String, action:String, label:String):Client { })
	@:overload(function(category:String, action:String, label:String, ?callback:Dynamic -> Void):Void { })
	@:overload(function(category:String, action:String, label:String, value:Dynamic):Client { })
	@:overload(function(category:String, action:String, label:String, value:Dynamic, ?callback:Dynamic -> Void):Void { })
	@:overload(function(category:String, action:String, label:String, value:Dynamic, params:Dynamic, ?callback:Dynamic -> Void):Void { })
	@:overload(function(params:Dynamic):Client { })
	@:overload(function(params:Dynamic, callback:Dynamic -> Void):Void { })
	function event(category:String, action:String):Client;
	@:overload(function(id:String, callback:Dynamic -> Void):Void { })
	@:overload(function(id:String, revenue:Float):Client { })
	@:overload(function(id:String, revenue:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(id:String, revenue:Float, shipping:Float):Client { })
	@:overload(function(id:String, revenue:Float, shipping:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(id:String, revenue:Float, shipping:Float, taxping:Float):Client { })
	@:overload(function(id:String, revenue:Float, shipping:Float, taxping:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(id:String, revenue:Float, shipping:Float, taxping:Float, affiliation:String):Client { })
	@:overload(function(id:String, revenue:Float, shipping:Float, taxping:Float, affiliation:String, callback:Dynamic -> Void):Void { })
	@:overload(function(params:Dynamic):Client { })
	@:overload(function(params:Dynamic, callback:Dynamic -> Void):Void { })
	function transaction(id:String):Client;
	@:overload(function(price:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(price:Float, quantity:Float):Client { })
	@:overload(function(price:Float, quantity:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(price:Float, quantity:Float, sku:Float):Client { })
	@:overload(function(price:Float, quantity:Float, sku:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(price:Float, quantity:Float, sku:Float, name:String):Client { })
	@:overload(function(price:Float, quantity:Float, sku:Float, name:String, callback:Dynamic -> Void):Void { })
	@:overload(function(price:Float, quantity:Float, sku:Float, name:String, variation:String):Client { })
	@:overload(function(price:Float, quantity:Float, sku:Float, name:String, variation:String, callback:Dynamic -> Void):Void { })
	@:overload(function(price:Float, quantity:Float, sku:Float, name:String, variation:String, params:Dynamic):Client { })
	@:overload(function(price:Float, quantity:Float, sku:Float, name:String, variation:String, params:Dynamic, callback:Dynamic -> Void):Void { })
	@:overload(function(params:Dynamic):Client { })
	@:overload(function(params:Dynamic, callback:Dynamic -> Void):Void { })
	function item(price:Float):Client;
	@:overload(function(description:String, callback:Dynamic -> Void):Void { })
	@:overload(function(description:String, fatal:Bool):Client { })
	@:overload(function(description:String, fatal:Bool, callback:Dynamic -> Void):Void { })
	@:overload(function(params:Dynamic):Client { })
	@:overload(function(params:Dynamic, callback:Dynamic -> Void):Void { })
	function exception(description:String):Client;
	@:overload(function(category:String, callback:Dynamic -> Void):Void { })
	@:overload(function(category:String, variable:String):Client { })
	@:overload(function(category:String, variable:String, callback:Dynamic -> Void):Void { })
	@:overload(function(category:String, variable:String, time:Float):Client { })
	@:overload(function(category:String, variable:String, time:Float, callback:Dynamic -> Void):Void { })
	@:overload(function(category:String, variable:String, time:Float, label:String):Client { })
	@:overload(function(category:String, variable:String, time:Float, label:String, callback:Dynamic -> Void):Void { })
	@:overload(function(params:Dynamic):Client { })
	@:overload(function(params:Dynamic, callback:Dynamic -> Void):Void { })
	function timing(category:String):Client;
	function middleware(accountID:String, ?options:Dynamic):Dynamic;
};
