extern class ModuleTopLevel {
	static function print(str:String):Void;
	static function printErr(str:String):Void;
	static var arguments : Array<String>;
	static var preInit : Array<{ }>;
	static var preRun : Array<{ }>;
	static var postRun : Array<{ }>;
	static var noExitRuntime : Bool;
	static var Runtime : Dynamic;
	static function ccall(ident:String, returnType:String, argTypes:Array<String>, args:Array<Dynamic>):Dynamic;
	static function cwrap(ident:String, returnType:String, argTypes:Array<String>):Dynamic;
	static function setValue(ptr:Float, value:Dynamic, type:String, noSafe:Bool):Void;
	static function getValue(ptr:Float, type:String, noSafe:Bool):Dynamic;
	static var ALLOC_NORMAL : Float;
	static var ALLOC_STACK : Float;
	static var ALLOC_STATIC : Float;
	static var ALLOC_DYNAMIC : Float;
	static var ALLOC_NONE : Float;
	static function allocate(slab:Dynamic, types:String, allocator:Float, ptr:Float):Float;
	static function allocate(slab:Dynamic, types:Array<String>, allocator:Float, ptr:Float):Float;
	static function Pointer_stringify(ptr:Float, ?length:Float):String;
	static function UTF16ToString(ptr:Float):String;
	static function stringToUTF16(str:String, outPtr:Float):Void;
	static function UTF32ToString(ptr:Float):String;
	static function stringToUTF32(str:String, outPtr:Float):Void;
	static var HEAP : Int32Array;
	static var IHEAP : Int32Array;
	static var FHEAP : Float64Array;
	static var HEAP8 : Int8Array;
	static var HEAP16 : Int16Array;
	static var HEAP32 : Int32Array;
	static var HEAPU8 : Uint8Array;
	static var HEAPU16 : Uint16Array;
	static var HEAPU32 : Uint32Array;
	static var HEAPF32 : Float32Array;
	static var HEAPF64 : Float64Array;
	static var TOTAL_STACK : Float;
	static var TOTAL_MEMORY : Float;
	static var FAST_MEMORY : Float;
	static function addOnPreRun(cb:Void -> Dynamic):Void;
	static function addOnInit(cb:Void -> Dynamic):Void;
	static function addOnPreMain(cb:Void -> Dynamic):Void;
	static function addOnExit(cb:Void -> Dynamic):Void;
	static function addOnPostRun(cb:Void -> Dynamic):Void;
	static function intArrayFromString(stringy:String, ?dontAddNull:Bool, ?length:Float):Array<Float>;
	static function intArrayToString(array:Array<Float>):String;
	static function writeStringToMemory(str:String, buffer:Float, dontAddNull:Bool):Void;
	static function writeArrayToMemory(array:Array<Float>, buffer:Float):Void;
	static function writeAsciiToMemory(str:String, buffer:Float, dontAddNull:Bool):Void;
	static function addRunDependency(id:Dynamic):Void;
	static function removeRunDependency(id:Dynamic):Void;
	static var preloadedImages : Dynamic;
	static var preloadedAudios : Dynamic;
	static function _malloc(size:Float):Float;
	static function _free(ptr:Float):Void;
}
