extern class UITopLevel {
	static var ANIMATION_CURVE_EASE_IN : Float;
	static var ANIMATION_CURVE_EASE_IN_OUT : Float;
	static var ANIMATION_CURVE_EASE_OUT : Float;
	static var ANIMATION_CURVE_LINEAR : Float;
	static var AUTODETECT_ADDRESS : Float;
	static var AUTODETECT_ALL : Float;
	static var AUTODETECT_CALENDAR : Float;
	static var AUTODETECT_LINK : Float;
	static var AUTODETECT_NONE : Float;
	static var AUTODETECT_PHONE : Float;
	static var AUTOLINK_ALL : Float;
	static var AUTOLINK_CALENDAR : Float;
	static var AUTOLINK_EMAIL_ADDRESSES : Float;
	static var AUTOLINK_MAP_ADDRESSES : Float;
	static var AUTOLINK_NONE : Float;
	static var AUTOLINK_PHONE_NUMBERS : Float;
	static var AUTOLINK_URLS : Float;
	static var BLEND_MODE_CLEAR : Float;
	static var BLEND_MODE_COLOR : Float;
	static var BLEND_MODE_COLOR_BURN : Float;
	static var BLEND_MODE_COLOR_DODGE : Float;
	static var BLEND_MODE_COPY : Float;
	static var BLEND_MODE_DARKEN : Float;
	static var BLEND_MODE_DESTINATION_ATOP : Float;
	static var BLEND_MODE_DESTINATION_IN : Float;
	static var BLEND_MODE_DESTINATION_OUT : Float;
	static var BLEND_MODE_DESTINATION_OVER : Float;
	static var BLEND_MODE_DIFFERENCE : Float;
	static var BLEND_MODE_EXCLUSION : Float;
	static var BLEND_MODE_HARD_LIGHT : Float;
	static var BLEND_MODE_HUE : Float;
	static var BLEND_MODE_LIGHTEN : Float;
	static var BLEND_MODE_LUMINOSITY : Float;
	static var BLEND_MODE_MULTIPLY : Float;
	static var BLEND_MODE_NORMAL : Float;
	static var BLEND_MODE_OVERLAY : Float;
	static var BLEND_MODE_PLUS_DARKER : Float;
	static var BLEND_MODE_PLUS_LIGHTER : Float;
	static var BLEND_MODE_SATURATION : Float;
	static var BLEND_MODE_SCREEN : Float;
	static var BLEND_MODE_SOFT_LIGHT : Float;
	static var BLEND_MODE_SOURCE_ATOP : Float;
	static var BLEND_MODE_SOURCE_IN : Float;
	static var BLEND_MODE_SOURCE_OUT : Float;
	static var BLEND_MODE_XOR : Float;
	static var EXTEND_EDGE_ALL : Float;
	static var EXTEND_EDGE_BOTTOM : Float;
	static var EXTEND_EDGE_LEFT : Float;
	static var EXTEND_EDGE_NONE : Float;
	static var EXTEND_EDGE_RIGHT : Float;
	static var EXTEND_EDGE_TOP : Float;
	static var FACE_DOWN : Float;
	static var FACE_UP : Float;
	static var FILL : String;
	static var INHERIT : String;
	static var INPUT_BORDERSTYLE_BEZEL : Float;
	static var INPUT_BORDERSTYLE_LINE : Float;
	static var INPUT_BORDERSTYLE_NONE : Float;
	static var INPUT_BORDERSTYLE_ROUNDED : Float;
	static var INPUT_BUTTONMODE_ALWAYS : Float;
	static var INPUT_BUTTONMODE_NEVER : Float;
	static var INPUT_BUTTONMODE_ONBLUR : Float;
	static var INPUT_BUTTONMODE_ONFOCUS : Float;
	static var KEYBOARD_APPEARANCE_ALERT : Float;
	static var KEYBOARD_APPEARANCE_DEFAULT : Float;
	static var KEYBOARD_ASCII : Float;
	static var KEYBOARD_DECIMAL_PAD : Float;
	static var KEYBOARD_DEFAULT : Float;
	static var KEYBOARD_EMAIL : Float;
	static var KEYBOARD_NAMEPHONE_PAD : Float;
	static var KEYBOARD_NUMBERS_PUNCTUATION : Float;
	static var KEYBOARD_NUMBER_PAD : Float;
	static var KEYBOARD_PHONE_PAD : Float;
	static var KEYBOARD_URL : Float;
	static var LANDSCAPE_LEFT : Float;
	static var LANDSCAPE_RIGHT : Float;
	static var LIST_ACCESSORY_TYPE_CHECKMARK : Float;
	static var LIST_ACCESSORY_TYPE_DETAIL : Float;
	static var LIST_ACCESSORY_TYPE_DISCLOSURE : Float;
	static var LIST_ACCESSORY_TYPE_NONE : Float;
	static var LIST_ITEM_TEMPLATE_CONTACTS : Float;
	static var LIST_ITEM_TEMPLATE_DEFAULT : Float;
	static var LIST_ITEM_TEMPLATE_SETTINGS : Float;
	static var LIST_ITEM_TEMPLATE_SUBTITLE : Float;
	static var NOTIFICATION_DURATION_LONG : Float;
	static var NOTIFICATION_DURATION_SHORT : Float;
	static var PICKER_TYPE_COUNT_DOWN_TIMER : Float;
	static var PICKER_TYPE_DATE : Float;
	static var PICKER_TYPE_DATE_AND_TIME : Float;
	static var PICKER_TYPE_PLAIN : Float;
	static var PICKER_TYPE_TIME : Float;
	static var PORTRAIT : Float;
	static var RETURNKEY_DEFAULT : Float;
	static var RETURNKEY_DONE : Float;
	static var RETURNKEY_EMERGENCY_CALL : Float;
	static var RETURNKEY_GO : Float;
	static var RETURNKEY_GOOGLE : Float;
	static var RETURNKEY_JOIN : Float;
	static var RETURNKEY_NEXT : Float;
	static var RETURNKEY_ROUTE : Float;
	static var RETURNKEY_SEARCH : Float;
	static var RETURNKEY_SEND : Float;
	static var RETURNKEY_YAHOO : Float;
	static var SIZE : String;
	static var TEXT_ALIGNMENT_CENTER : Dynamic;
	static var TEXT_ALIGNMENT_LEFT : Dynamic;
	static var TEXT_ALIGNMENT_RIGHT : Dynamic;
	static var TEXT_AUTOCAPITALIZATION_ALL : Float;
	static var TEXT_AUTOCAPITALIZATION_NONE : Float;
	static var TEXT_AUTOCAPITALIZATION_SENTENCES : Float;
	static var TEXT_AUTOCAPITALIZATION_WORDS : Float;
	static var TEXT_STYLE_BODY : String;
	static var TEXT_STYLE_CAPTION1 : String;
	static var TEXT_STYLE_CAPTION2 : String;
	static var TEXT_STYLE_FOOTNOTE : String;
	static var TEXT_STYLE_HEADLINE : String;
	static var TEXT_STYLE_SUBHEADLINE : String;
	static var TEXT_VERTICAL_ALIGNMENT_BOTTOM : Dynamic;
	static var TEXT_VERTICAL_ALIGNMENT_CENTER : Dynamic;
	static var TEXT_VERTICAL_ALIGNMENT_TOP : Dynamic;
	static var UNIT_CM : String;
	static var UNIT_DIP : String;
	static var UNIT_IN : String;
	static var UNIT_MM : String;
	static var UNIT_PX : String;
	static var UNKNOWN : Float;
	static var UPSIDE_PORTRAIT : Float;
	static var URL_ERROR_AUTHENTICATION : Float;
	static var URL_ERROR_BAD_URL : Float;
	static var URL_ERROR_CONNECT : Float;
	static var URL_ERROR_FILE : Float;
	static var URL_ERROR_FILE_NOT_FOUND : Float;
	static var URL_ERROR_HOST_LOOKUP : Float;
	static var URL_ERROR_REDIRECT_LOOP : Float;
	static var URL_ERROR_SSL_FAILED : Float;
	static var URL_ERROR_TIMEOUT : Float;
	static var URL_ERROR_UNKNOWN : Float;
	static var URL_ERROR_UNSUPPORTED_SCHEME : Float;
	static var apiName : String;
	static var backgroundColor : String;
	static var backgroundImage : String;
	static var bubbleParent : Bool;
	static var currentTab : Ti.UI.Tab;
	static var currentWindow : Ti.UI.Window;
	static var orientation : Float;
	static function addEventListener(name:String, callback:haxe.extern.Rest<Dynamic> -> Dynamic):Void;
	static function applyProperties(props:Dictionary<Dynamic>):Void;
	static function convertUnits(convertFromValue:String, convertToUnits:Float):Float;
	static function create2DMatrix(?parameters:MatrixCreationDict):Ti.UI._2DMatrix;
	static function create3DMatrix(?parameters:Dictionary<Ti.UI._3DMatrix>):Ti.UI._3DMatrix;
	static function createActivityIndicator(?parameters:Dictionary<Ti.UI.ActivityIndicator>):Ti.UI.ActivityIndicator;
	static function createAlertDialog(?parameters:Dictionary<Ti.UI.AlertDialog>):Ti.UI.AlertDialog;
	static function createAnimation(?parameters:Dictionary<Ti.UI.Animation>):Ti.UI.Animation;
	static function createButton(?parameters:Dictionary<Ti.UI.Button>):Ti.UI.Button;
	static function createButtonBar(?parameters:Dictionary<Ti.UI.ButtonBar>):Ti.UI.ButtonBar;
	static function createCoverFlowView(?parameters:Dictionary<Ti.UI.CoverFlowView>):Ti.UI.CoverFlowView;
	static function createDashboardItem(?parameters:Dictionary<Ti.UI.DashboardItem>):Ti.UI.DashboardItem;
	static function createDashboardView(?parameters:Dictionary<Ti.UI.DashboardView>):Ti.UI.DashboardView;
	static function createEmailDialog(?parameters:Dictionary<Ti.UI.EmailDialog>):Ti.UI.EmailDialog;
	static function createImageView(?parameters:Dictionary<Ti.UI.ImageView>):Ti.UI.ImageView;
	static function createLabel(?parameters:Dictionary<Ti.UI.Label>):Ti.UI.Label;
	static function createListSection(?parameters:Dictionary<Ti.UI.ListSection>):Ti.UI.ListSection;
	static function createListView(?parameters:Dictionary<Ti.UI.ListView>):Ti.UI.ListView;
	static function createMaskedImage(?parameters:Dictionary<Ti.UI.MaskedImage>):Ti.UI.MaskedImage;
	static function createNotification(?parameters:Dictionary<Ti.UI.Notification>):Ti.UI.Notification;
	static function createOptionDialog(?parameters:Dictionary<Ti.UI.OptionDialog>):Ti.UI.OptionDialog;
	static function createPicker(?parameters:Dictionary<Ti.UI.Picker>):Ti.UI.Picker;
	static function createPickerColumn(?parameters:Dictionary<Ti.UI.PickerColumn>):Ti.UI.PickerColumn;
	static function createPickerRow(?parameters:Dictionary<Ti.UI.PickerRow>):Ti.UI.PickerRow;
	static function createProgressBar(?parameters:Dictionary<Ti.UI.ProgressBar>):Ti.UI.ProgressBar;
	static function createRefreshControl(?parameters:Dictionary<Ti.UI.RefreshControl>):Ti.UI.RefreshControl;
	static function createSMSDialog(?parameters:Dictionary<Ti.UI.SMSDialog>):Ti.UI.SMSDialog;
	static function createScrollView(?parameters:Dictionary<Ti.UI.ScrollView>):Ti.UI.ScrollView;
	static function createScrollableView(?parameters:Dictionary<Ti.UI.ScrollableView>):Ti.UI.ScrollableView;
	static function createSearchBar(?parameters:Dictionary<Ti.UI.SearchBar>):Ti.UI.SearchBar;
	static function createSlider(?parameters:Dictionary<Ti.UI.Slider>):Ti.UI.Slider;
	static function createSwitch(?parameters:Dictionary<Ti.UI.Switch>):Ti.UI.Switch;
	static function createTab(?parameters:Dictionary<Ti.UI.Tab>):Ti.UI.Tab;
	static function createTabGroup(?parameters:Dictionary<Ti.UI.TabGroup>):Ti.UI.TabGroup;
	static function createTabbedBar(?parameters:Dictionary<Ti.UI.TabbedBar>):Ti.UI.TabbedBar;
	static function createTableView(?parameters:Dictionary<Ti.UI.TableView>):Ti.UI.TableView;
	static function createTableViewRow(?parameters:Dictionary<Ti.UI.TableViewRow>):Ti.UI.TableViewRow;
	static function createTableViewSection(?parameters:Dictionary<Ti.UI.TableViewSection>):Ti.UI.TableViewSection;
	static function createTextArea(?parameters:Dictionary<Ti.UI.TextArea>):Ti.UI.TextArea;
	static function createTextField(?parameters:Dictionary<Ti.UI.TextField>):Ti.UI.TextField;
	static function createToolbar(?parameters:Dictionary<Ti.UI.Toolbar>):Ti.UI.Toolbar;
	static function createView(?parameters:Dictionary<Ti.UI.View>):Ti.UI.View;
	static function createWebView(?parameters:Dictionary<Ti.UI.WebView>):Ti.UI.WebView;
	static function createWindow(?parameters:Dictionary<Ti.UI.Window>):Ti.UI.Window;
	static function fireEvent(name:String, event:Dictionary<Dynamic>):Void;
	static function getApiName():String;
	static function getBackgroundColor():String;
	static function getBackgroundImage():String;
	static function getBubbleParent():Bool;
	static function getCurrentTab():Ti.UI.Tab;
	static function getCurrentWindow():Ti.UI.Window;
	static function getOrientation():Float;
	static function removeEventListener(name:String, callback:haxe.extern.Rest<Dynamic> -> Dynamic):Void;
	static function setBackgroundColor(backgroundColor:String):Void;
	static function setBackgroundImage(backgroundImage:String):Void;
	static function setBubbleParent(bubbleParent:Bool):Void;
	static function setCurrentTab(currentTab:Ti.UI.Tab):Void;
	static function setOrientation(orientation:Float):Void;
}
